INSERT INTO public."Game Content" (contentId, game, description, contentJson)

VALUES
  -- Game
   ('ef64acee-d36e-45fc-b148-ef35baaa9bc9', 'jawsOfTheLion', 'Game Summary', '{"name":"Jaws of the Lion","code":"jawsOfTheLion","kind":"game"}')

  -- Scenarios
  ,('817ec5a9-e0a8-4d23-a038-1e29ea217587', 'jawsOfTheLion', 'Scenario - Roadside Ambush', '{"code":"roadside_ambush", "name":"Roadside Ambush", "kind": "scenario", "scenarioNumber": 1, "monsters": ["vermling_raider"]}')
  ,('649e24aa-6c4b-4bd7-b53d-0ae7a40095bf', 'jawsOfTheLion', 'Scenario - A Hole in the Wall', '{"code":"a_hole_in_the_wall", "name":"A Hole in the Wall", "kind": "scenario", "scenarioNumber": 2, "monsters": ["vermling_raider"]}')
  ,('0bc67987-cf81-4857-a6b5-c89257569398', 'jawsOfTheLion', 'Scenario - The Black Ship', '{"code":"the_black_ship", "name":"The Black Ship", "kind": "scenario", "scenarioNumber": 3, "monsters": ["giant_viper", "zealot"]}')
  ,('74a5b389-cd56-46cc-9932-281b79965dda', 'jawsOfTheLion', 'Scenario - A Ritual in Stone', '{"code":"a_ritual_in_stone", "name":"A Ritual in Stone", "kind": "scenario", "scenarioNumber": 4, "monsters": ["stone_golem", "zealot"]}')
  ,('c749981f-858c-44da-a1d6-1f22ad4b86b9', 'jawsOfTheLion', 'Scenario - A Deeper Understanding', '{"code":"a_deeper_understanding", "name":"A Deeper Understanding", "kind": "scenario", "scenarioNumber": 5, "monsters": ["blood_tumor", "chaos_demon", "zealot"]}')
  ,('eb684cb3-496d-4145-b845-c4e70702f990', 'jawsOfTheLion', 'Scenario - Corrupted Research', '{"code":"corrupted_research", "name":"Corrupted Research", "kind": "scenario", "scenarioNumber": 6, "monsters": ["rat_monstrosity", "black_sludge"]}')
  ,('7596e37f-c5ab-4eb7-bd99-9e5793341673', 'jawsOfTheLion', 'Scenario - Sunken Tumor', '{"code":"sunken_tumor", "name":"Sunken Tumor", "kind": "scenario", "scenarioNumber":7, "monsters": ["blood_tumor", "vermling_scout", "zealot"]}')
  ,('270f0bf8-ccb6-4bae-b50a-f73b36e1c771', 'jawsOfTheLion', 'Scenario - Hidden Tumor', '{"code":"hidden_tumor", "name":"Hidden Tumor", "kind": "scenario", "scenarioNumber":8, "monsters": ["blood_tumor", "chaos_demon", "zealot"]}')
  ,('0493c103-a3ff-4522-9866-1b90c3fe9396', 'jawsOfTheLion', 'Scenario - Explosive Evolution', '{"code":"explosive_evolution", "name":"Explosive Evolution", "kind": "scenario", "scenarioNumber":9, "monsters": ["blood_horror", "living_corpse", "zealot"]}')
  ,('0ddcec12-98ac-4948-99bd-ec6b14a33de6', 'jawsOfTheLion', 'Scenario - The Gauntlet', '{"code":"the_gauntlet", "name":"The Gauntlet", "kind": "scenario", "scenarioNumber":10, "monsters": ["black_sludge", "chaos_demon", "stone_golem"]}')
  ,('ac422f26-3d1d-4655-8987-b61f88863d1a', 'jawsOfTheLion', 'Scenario - Defiled Sewers', '{"code":"defiled_sewers", "name":"Defiled Sewers", "kind": "scenario", "scenarioNumber":11, "monsters": ["black_sludge", "giant_viper", "vermling_scout"]}')
  ,('9897dece-ccbb-4fd3-919f-9a2a7ee2e803', 'jawsOfTheLion', 'Scenario - Beguiling Sewers', '{"code":"beguiling_sewers", "name":"Beguiling Sewers", "kind": "scenario", "scenarioNumber":12, "monsters": ["living_corpse", "living_spirit"]}')

  -- Player
  ,('5905b80d-f9c1-4ba2-bf2f-b686c5781af6', 'jawsOfTheLion', 'Player - Red Guard', '{"name":"Red Guard","code":"red_guard","kind":"player","baseStats":{"levels":[{"experience":0,"level":1},{"experience":45,"level":2},{"experience":95,"level":3},{"experience":150,"level":4},{"experience":210,"level":5},{"experience":275,"level":6},{"experience":345,"level":7},{"experience":420,"level":8},{"experience":500,"level":9}],"health":[{"level":1,"health":10},{"level":2,"health":12},{"level":3,"health":14},{"level":4,"health":16},{"level":5,"health":18},{"level":6,"health":20},{"level":7,"health":22},{"level":8,"health":24},{"level":9,"health":26}]}}')
  ,('ad7a72bd-522b-4edb-8903-606719b36082', 'jawsOfTheLion', 'Player - Voidwarden', '{"name":"Voidwarden","code":"voidwarden","kind":"player","baseStats":{"levels":[{"experience":0,"level":1},{"experience":45,"level":2},{"experience":95,"level":3},{"experience":150,"level":4},{"experience":210,"level":5},{"experience":275,"level":6},{"experience":345,"level":7},{"experience":420,"level":8},{"experience":500,"level":9}],"health":[{"level":1,"health":6},{"level":2,"health":7},{"level":3,"health":8},{"level":4,"health":9},{"level":5,"health":10},{"level":6,"health":11},{"level":7,"health":12},{"level":8,"health":13},{"level":9,"health":14}]}}')
  ,('53499c72-442d-409d-bbd1-40315c868014', 'jawsOfTheLion', 'Player - Hatchet', '{"name":"Hatchet","code":"hatchet","kind":"player","baseStats":{"levels":[{"experience":0,"level":1},{"experience":45,"level":2},{"experience":95,"level":3},{"experience":150,"level":4},{"experience":210,"level":5},{"experience":275,"level":6},{"experience":345,"level":7},{"experience":420,"level":8},{"experience":500,"level":9}],"health":[{"level":1,"health":8},{"level":2,"health":9},{"level":3,"health":11},{"level":4,"health":12},{"level":5,"health":14},{"level":6,"health":15},{"level":7,"health":17},{"level":8,"health":18},{"level":9,"health":20}]}}')
  ,('97750f16-7bfe-4425-a30a-12685636313f', 'jawsOfTheLion', 'Player - Demolitionist', '{"name":"Demolitionist","code":"demolitionist","kind":"player","baseStats":{"levels":[{"experience":0,"level":1},{"experience":45,"level":2},{"experience":95,"level":3},{"experience":150,"level":4},{"experience":210,"level":5},{"experience":275,"level":6},{"experience":345,"level":7},{"experience":420,"level":8},{"experience":500,"level":9}],"health":[{"level":1,"health":8},{"level":2,"health":9},{"level":3,"health":11},{"level":4,"health":12},{"level":5,"health":14},{"level":6,"health":15},{"level":7,"health":17},{"level":8,"health":18},{"level":9,"health":20}]}}')

  -- Monsters - Regular
  ,('be660361-67d2-49ba-a42d-366ca1f1b9ad', 'jawsOfTheLion', 'Monster - Vermling Raider', '{"name":"Vermling Raider","code":"vermling_raider","kind":"monster","baseStats":{"standard":[{"level":0,"health":4,"movement":1,"attack":2,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":1,"health":5,"movement":1,"attack":2,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":2,"health":9,"movement":2,"attack":2,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":3,"health":11,"movement":3,"attack":2,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":4,"health":12,"movement":3,"attack":3,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":5,"health":15,"movement":3,"attack":3,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":6,"health":17,"movement":4,"attack":3,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":7,"health":17,"movement":4,"attack":3,"defenseEffects":[],"attackEffects":[],"immunity":[]}],"elite":[{"level":0,"health":8,"movement":1,"attack":2,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":1,"health":10,"movement":1,"attack":2,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":2,"health":14,"movement":3,"attack":3,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":3,"health":16,"movement":3,"attack":4,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":4,"health":19,"movement":4,"attack":4,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":5,"health":23,"movement":4,"attack":4,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":6,"health":27,"movement":4,"attack":5,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":7,"health":31,"movement":4,"attack":6,"defenseEffects":[],"attackEffects":[],"immunity":[]}]}}') 
  ,('c41117fd-0050-4622-8c17-e80cc8c13f59', 'jawsOfTheLion', 'Monster - Vermling Scout', '{"name":"Vermling Scout","code":"vermling_scout","kind":"monster","baseStats":{"standard":[{"level":0,"health":2,"movement":3,"attack":1,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":1,"health":3,"movement":3,"attack":1,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":2,"health":3,"movement":3,"attack":2,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":3,"health":5,"movement":3,"attack":2,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":4,"health":6,"movement":3,"attack":3,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":5,"health":8,"movement":3,"attack":3,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":6,"health":10,"movement":4,"attack":3,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":7,"health":13,"movement":4,"attack":3,"defenseEffects":[],"attackEffects":[],"immunity":[]}],"elite":[{"level":0,"health":4,"movement":3,"attack":2,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":1,"health":5,"movement":3,"attack":2,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":2,"health":5,"movement":4,"attack":3,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":3,"health":7,"movement":4,"attack":3,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":4,"health":8,"movement":4,"attack":4,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":5,"health":11,"movement":4,"attack":4,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":6,"health":13,"movement":5,"attack":4,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":7,"health":17,"movement":5,"attack":4,"defenseEffects":[],"attackEffects":[],"immunity":[]}]}}')
  ,('46ca0cbd-bb92-48f4-b7d3-44b62240ba21', 'jawsOfTheLion', 'Monster - Giant Viper', '{"name":"Giant Viper","code":"giant_viper","kind":"monster","baseStats":{"standard":[{"level":0,"health":2,"movement":2,"attack":1,"defenseEffects":[],"attackEffects":[{"type":"poison","duration":1,"value":-1}],"immunity":[]},{"level":1,"health":3,"movement":2,"attack":1,"defenseEffects":[],"attackEffects":[{"type":"poison","duration":1,"value":-1}],"immunity":[]},{"level":2,"health":4,"movement":3,"attack":1,"defenseEffects":[],"attackEffects":[{"type":"poison","duration":1,"value":-1}],"immunity":[]},{"level":3,"health":4,"movement":3,"attack":2,"defenseEffects":[],"attackEffects":[{"type":"poison","duration":1,"value":-1}],"immunity":[]},{"level":4,"health":6,"movement":3,"attack":2,"defenseEffects":[],"attackEffects":[{"type":"poison","duration":1,"value":-1}],"immunity":[]},{"level":5,"health":7,"movement":3,"attack":3,"defenseEffects":[],"attackEffects":[{"type":"poison","duration":1,"value":-1}],"immunity":[]},{"level":6,"health":8,"movement":4,"attack":3,"defenseEffects":[],"attackEffects":[{"type":"poison","duration":1,"value":-1}],"immunity":[]},{"level":7,"health":10,"movement":4,"attack":3,"defenseEffects":[],"attackEffects":[{"type":"poison","duration":1,"value":-1}],"immunity":[]}],"elite":[{"level":0,"health":3,"movement":2,"attack":2,"defenseEffects":[],"attackEffects":[{"type":"poison","duration":1,"value":-1}],"immunity":[]},{"level":1,"health":5,"movement":2,"attack":2,"defenseEffects":[],"attackEffects":[{"type":"poison","duration":1,"value":-1}],"immunity":[]},{"level":2,"health":7,"movement":3,"attack":2,"defenseEffects":[],"attackEffects":[{"type":"poison","duration":1,"value":-1}],"immunity":[]},{"level":3,"health":8,"movement":3,"attack":3,"defenseEffects":[],"attackEffects":[{"type":"poison","duration":1,"value":-1}],"immunity":[]},{"level":4,"health":11,"movement":3,"attack":3,"defenseEffects":[],"attackEffects":[{"type":"poison","duration":1,"value":-1}],"immunity":[]},{"level":5,"health":13,"movement":4,"attack":3,"defenseEffects":[],"attackEffects":[{"type":"poison","duration":1,"value":-1}],"immunity":[]},{"level":6,"health":14,"movement":4,"attack":4,"defenseEffects":[],"attackEffects":[{"type":"poison","duration":1,"value":-1}],"immunity":[]},{"level":7,"health":18,"movement":4,"attack":4,"defenseEffects":[],"attackEffects":[{"type":"poison","duration":1,"value":-1}],"immunity":[]}]}}')
  ,('96517170-650e-44b1-bd14-51fecb343620', 'jawsOfTheLion', 'Monster - Zealot', '{"name":"Zealot","code":"zealot","kind":"monster","baseStats":{"standard":[{"level":0,"health":4,"movement":2,"attack":2,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":1,"health":6,"movement":2,"attack":2,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":2,"health":7,"movement":3,"attack":3,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":3,"health":8,"movement":3,"attack":3,"defenseEffects":[],"attackEffects":[{"type":"wound","duration":"1","value":-1}],"immunity":[]},{"level":4,"health":10,"movement":3,"attack":3,"defenseEffects":[],"attackEffects":[{"type":"wound","duration":"1","value":-1}],"immunity":[]},{"level":5,"health":12,"movement":4,"attack":3,"defenseEffects":[],"attackEffects":[{"type":"wound","duration":"1","value":-1}],"immunity":[]},{"level":6,"health":14,"movement":4,"attack":4,"defenseEffects":[],"attackEffects":[{"type":"wound","duration":"1","value":-1}],"immunity":[]},{"level":7,"health":16,"movement":4,"attack":5,"defenseEffects":[],"attackEffects":[{"type":"wound","duration":"1","value":-1}]}],"elite":[{"level":0,"health":7,"movement":2,"attack":3,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":1,"health":8,"movement":2,"attack":3,"defenseEffects":[],"attackEffects":[{"type":"wound","duration":"1","value":-1}],"immunity":[]},{"level":2,"health":11,"movement":3,"attack":3,"defenseEffects":[],"attackEffects":[{"type":"wound","duration":"1","value":-1}],"immunity":[]},{"level":3,"health":13,"movement":3,"attack":4,"defenseEffects":[],"attackEffects":[{"type":"wound","duration":"1","value":-1}],"immunity":[]},{"level":4,"health":17,"movement":3,"attack":4,"defenseEffects":[],"attackEffects":[{"type":"wound","duration":"1","value":-1}],"immunity":[]},{"level":5,"health":18,"movement":4,"attack":5,"defenseEffects":[],"attackEffects":[{"type":"wound","duration":"1","value":-1}],"immunity":[]},{"level":6,"health":22,"movement":4,"attack":6,"defenseEffects":[],"attackEffects":[{"type":"wound","duration":"1","value":-1}],"immunity":[]},{"level":7,"health":26,"movement":4,"attack":7,"defenseEffects":[],"attackEffects":[{"type":"wound","duration":"1","value":-1}]}]}}')
  ,('194abd1c-ad53-4cc2-841b-747fccd540ef', 'jawsOfTheLion', 'Monster - Stone Golem', '{"name":"Stone Golem","code":"stone_golem","kind":"monster","baseStats":{"standard":[{"level":0,"health":10,"movement":1,"attack":3,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":1,"health":10,"movement":1,"attack":3,"defenseEffects":[{"type":"shield","value":"1","duration":-1}],"attackEffects":[],"immunity":[]},{"level":2,"health":11,"movement":1,"attack":4,"defenseEffects":[{"type":"shield","value":"1","duration":-1}],"attackEffects":[],"immunity":[]},{"level":3,"health":11,"movement":1,"attack":4,"defenseEffects":[{"type":"shield","value":"2","duration":-1}],"attackEffects":[],"immunity":[]},{"level":4,"health":12,"movement":2,"attack":4,"defenseEffects":[{"type":"shield","value":"2","duration":-1}],"attackEffects":[],"immunity":[]},{"level":5,"health":13,"movement":2,"attack":5,"defenseEffects":[{"type":"shield","value":"2","duration":-1}],"attackEffects":[],"immunity":[]},{"level":6,"health":16,"movement":2,"attack":5,"defenseEffects":[{"type":"shield","value":"2","duration":-1}],"attackEffects":[],"immunity":[]},{"level":7,"health":16,"movement":2,"attack":5,"defenseEffects":[{"type":"shield","value":"3","duration":-1}],"attackEffects":[]}],"elite":[{"level":0,"health":10,"movement":2,"attack":4,"defenseEffects":[{"type":"shield","value":"1","duration":-1}],"attackEffects":[],"immunity":[]},{"level":1,"health":10,"movement":2,"attack":4,"defenseEffects":[{"type":"shield","value":"2","duration":-1}],"attackEffects":[],"immunity":[]},{"level":2,"health":13,"movement":2,"attack":5,"defenseEffects":[{"type":"shield","value":"2","duration":-1}],"attackEffects":[],"immunity":[]},{"level":3,"health":14,"movement":2,"attack":5,"defenseEffects":[{"type":"shield","value":"3","duration":-1}],"attackEffects":[],"immunity":[]},{"level":4,"health":16,"movement":2,"attack":6,"defenseEffects":[{"type":"shield","value":"3","duration":-1}],"attackEffects":[],"immunity":[]},{"level":5,"health":18,"movement":3,"attack":6,"defenseEffects":[{"type":"shield","value":"3","duration":-1}],"attackEffects":[],"immunity":[]},{"level":6,"health":20,"movement":3,"attack":7,"defenseEffects":[{"type":"shield","value":"3","duration":-1}],"attackEffects":[],"immunity":[]},{"level":7,"health":21,"movement":3,"attack":7,"defenseEffects":[{"type":"shield","value":"4","duration":-1}],"attackEffects":[]}]}}')
  ,('f3b10230-3e24-4c7b-8cf4-7d9e35aa194d', 'jawsOfTheLion', 'Monster - Rat Monstrosity', '{"name":"Rat Monstrosity","code":"rat_monstrosity","kind":"monster","baseStats":{"standard":[{"level":0,"health":4,"movement":1,"attack":1,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":1,"health":4,"movement":1,"attack":2,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":2,"health":5,"movement":2,"attack":2,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":3,"health":6,"movement":2,"attack":3,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":4,"health":8,"movement":2,"attack":3,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":5,"health":10,"movement":3,"attack":3,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":6,"health":12,"movement":3,"attack":3,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":7,"health":12,"movement":3,"attack":4,"defenseEffects":[],"attackEffects":[],"immunity":[]}],"elite":[{"level":0,"health":6,"movement":1,"attack":2,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":1,"health":7,"movement":1,"attack":2,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":2,"health":8,"movement":1,"attack":3,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":3,"health":10,"movement":2,"attack":3,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":4,"health":12,"movement":2,"attack":3,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":5,"health":13,"movement":2,"attack":4,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":6,"health":14,"movement":3,"attack":4,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":7,"health":16,"movement":3,"attack":5,"defenseEffects":[],"attackEffects":[],"immunity":[]}]}}')
  ,('4ea607b4-d5df-4ca1-a98b-17ca3d302125', 'jawsOfTheLion', 'Monster - Living Corpse', '{"name":"Living Corpse","code":"living_corpse","kind":"monster","baseStats":{"standard":[{"level":0,"health":5,"movement":1,"attack":3,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":1,"health":7,"movement":1,"attack":3,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":2,"health":9,"movement":1,"attack":3,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":3,"health":10,"movement":1,"attack":4,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":4,"health":11,"movement":2,"attack":4,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":5,"health":13,"movement":2,"attack":4,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":6,"health":14,"movement":2,"attack":4,"defenseEffects":[],"attackEffects":[{"type":"poison","duration":1,"value":-1}],"immunity":[]},{"level":7,"health":16,"movement":2,"attack":5,"defenseEffects":[],"attackEffects":[{"type":"poison","duration":1,"value":-1}],"immunity":[]}],"elite":[{"level":0,"health":10,"movement":1,"attack":3,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":1,"health":11,"movement":1,"attack":4,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":2,"health":14,"movement":1,"attack":4,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":3,"health":14,"movement":2,"attack":5,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":4,"health":16,"movement":2,"attack":5,"defenseEffects":[],"attackEffects":[{"type":"poison","duration":1,"value":-1}],"immunity":[]},{"level":5,"health":18,"movement":2,"attack":6,"defenseEffects":[],"attackEffects":[{"type":"poison","duration":1,"value":-1}],"immunity":[]},{"level":6,"health":23,"movement":2,"attack":6,"defenseEffects":[],"attackEffects":[{"type":"poison","duration":1,"value":-1}],"immunity":[]},{"level":7,"health":29,"movement":2,"attack":6,"defenseEffects":[],"attackEffects":[{"type":"poison","duration":1,"value":-1}],"immunity":[]}]}}')
  ,('0745492b-57fd-4fbc-8537-217314d8aa53', 'jawsOfTheLion', 'Monster - Black Imp', '{"name":"Black Imp","code":"black_imp","kind":"monster","baseStats":{"standard":[{"level":0,"health":3,"movement":1,"attack":1,"defenseEffects":[],"attackEffects":[{"type":"poison","duration":-1,"value":-1}],"immunity":[]},{"level":1,"health":4,"movement":1,"attack":1,"defenseEffects":[],"attackEffects":[{"type":"poison","duration":-1,"value":-1}],"immunity":[]},{"level":2,"health":5,"movement":1,"attack":1,"defenseEffects":[],"attackEffects":[{"type":"poison","duration":-1,"value":-1}],"immunity":[]},{"level":3,"health":5,"movement":1,"attack":2,"defenseEffects":[],"attackEffects":[{"type":"poison","duration":-1,"value":-1}],"immunity":[]},{"level":4,"health":7,"movement":1,"attack":2,"defenseEffects":[],"attackEffects":[{"type":"poison","duration":-1,"value":-1}],"immunity":[]},{"level":5,"health":9,"movement":1,"attack":2,"defenseEffects":[],"attackEffects":[{"type":"poison","duration":-1,"value":-1}],"immunity":[]},{"level":6,"health":10,"movement":1,"attack":3,"defenseEffects":[],"attackEffects":[{"type":"poison","duration":-1,"value":-1}],"immunity":[]},{"level":7,"health":13,"movement":1,"attack":3,"defenseEffects":[],"attackEffects":[{"type":"poison","duration":-1,"value":-1}],"immunity":[]}],"elite":[{"level":0,"health":4,"movement":1,"attack":2,"defenseEffects":[],"attackEffects":[{"type":"poison","duration":-1,"value":-1}],"immunity":[]},{"level":1,"health":6,"movement":1,"attack":2,"defenseEffects":[],"attackEffects":[{"type":"poison","duration":-1,"value":-1}],"immunity":[]},{"level":2,"health":8,"movement":1,"attack":2,"defenseEffects":[],"attackEffects":[{"type":"poison","duration":-1,"value":-1}],"immunity":[]},{"level":3,"health":8,"movement":1,"attack":3,"defenseEffects":[{"type":"disadvantage","duration":-1,"value":-1}],"attackEffects":[{"type":"poison","duration":-1,"value":-1}],"immunity":[]},{"level":4,"health":11,"movement":1,"attack":3,"defenseEffects":[{"type":"disadvantage","duration":-1,"value":-1}],"attackEffects":[{"type":"poison","duration":-1,"value":-1}],"immunity":[]},{"level":5,"health":14,"movement":1,"attack":3,"defenseEffects":[{"type":"disadvantage","duration":-1,"value":-1}],"attackEffects":[{"type":"poison","duration":-1,"value":-1}],"immunity":[]},{"level":6,"health":15,"movement":1,"attack":4,"defenseEffects":[{"type":"disadvantage","duration":-1,"value":-1}],"attackEffects":[{"type":"poison","duration":-1,"value":-1}],"immunity":[]},{"level":7,"health":19,"movement":1,"attack":4,"defenseEffects":[{"type":"disadvantage","duration":-1,"value":-1}],"attackEffects":[{"type":"poison","duration":-1,"value":-1}],"immunity":[]}]}}')
  ,('2109d9ae-c7df-4782-b310-90d9beaa72b3', 'jawsOfTheLion', 'Monster - Chaos Demon', '{"name":"Chaos Demon","code":"chaos_demon","kind":"monster","baseStats":{"standard":[{"level":0,"health":7,"movement":3,"attack":2,"defenseEffects":[],"attackEffects":[{"type":"muddle","duration":1,"value":-1}],"immunity":[]},{"level":1,"health":8,"movement":3,"attack":3,"defenseEffects":[],"attackEffects":[{"type":"muddle","duration":1,"value":-1}],"immunity":[]},{"level":2,"health":11,"movement":3,"attack":3,"defenseEffects":[],"attackEffects":[{"type":"muddle","duration":1,"value":-1}],"immunity":[]},{"level":3,"health":12,"movement":3,"attack":4,"defenseEffects":[],"attackEffects":[{"type":"muddle","duration":1,"value":-1}],"immunity":[]},{"level":4,"health":15,"movement":4,"attack":4,"defenseEffects":[],"attackEffects":[{"type":"muddle","duration":1,"value":-1}],"immunity":[]},{"level":5,"health":16,"movement":4,"attack":5,"defenseEffects":[],"attackEffects":[{"type":"muddle","duration":1,"value":-1}],"immunity":[]},{"level":6,"health":20,"movement":4,"attack":5,"defenseEffects":[],"attackEffects":[{"type":"muddle","duration":1,"value":-1}],"immunity":[]},{"level":7,"health":22,"movement":4,"attack":6,"defenseEffects":[],"attackEffects":[{"type":"muddle","duration":1,"value":-1}],"immunity":[]}],"elite":[{"level":0,"health":10,"movement":4,"attack":3,"defenseEffects":[],"attackEffects":[{"type":"muddle","duration":1,"value":-1}],"immunity":[]},{"level":1,"health":12,"movement":4,"attack":4,"defenseEffects":[],"attackEffects":[{"type":"muddle","duration":1,"value":-1}],"immunity":[]},{"level":2,"health":14,"movement":4,"attack":4,"defenseEffects":[],"attackEffects":[{"type":"muddle","duration":1,"value":-1}],"immunity":[]},{"level":3,"health":18,"movement":5,"attack":5,"defenseEffects":[],"attackEffects":[{"type":"muddle","duration":1,"value":-1}],"immunity":[]},{"level":4,"health":21,"movement":5,"attack":6,"defenseEffects":[],"attackEffects":[{"type":"muddle","duration":1,"value":-1}],"immunity":[]},{"level":5,"health":26,"movement":5,"attack":6,"defenseEffects":[],"attackEffects":[{"type":"muddle","duration":1,"value":-1}],"immunity":[]},{"level":6,"health":30,"movement":5,"attack":7,"defenseEffects":[],"attackEffects":[{"type":"muddle","duration":1,"value":-1}],"immunity":[]},{"level":7,"health":35,"movement":5,"attack":8,"defenseEffects":[],"attackEffects":[{"type":"muddle","duration":1,"value":-1}],"immunity":[]}]}}')
  ,('3bf628cf-28e6-4100-af03-caf0874b0335', 'jawsOfTheLion', 'Monster - Black Sludge', '{"name":"Black Sludge","code":"black_sludge","kind":"monster","baseStats":{"standard":[{"level":0,"health":4,"movement":1,"attack":2,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":1,"health":5,"movement":1,"attack":2,"defenseEffects":[{"type":"shield","duration":-1,"value":1}],"attackEffects":[],"immunity":[]},{"level":2,"health":7,"movement":1,"attack":2,"defenseEffects":[{"type":"shield","duration":-1,"value":1}],"attackEffects":[],"immunity":[]},{"level":3,"health":8,"movement":1,"attack":3,"defenseEffects":[{"type":"shield","duration":-1,"value":1}],"attackEffects":[],"immunity":[]},{"level":4,"health":9,"movement":2,"attack":3,"defenseEffects":[{"type":"shield","duration":-1,"value":1}],"attackEffects":[],"immunity":[]},{"level":5,"health":10,"movement":2,"attack":3,"defenseEffects":[{"type":"shield","duration":-1,"value":1}],"attackEffects":[{"type":"poison","duration":-1,"value":-1}],"immunity":[]},{"level":6,"health":12,"movement":2,"attack":4,"defenseEffects":[{"type":"shield","duration":-1,"value":1}],"attackEffects":[{"type":"poison","duration":-1,"value":-1}],"immunity":[]},{"level":7,"health":16,"movement":2,"attack":4,"defenseEffects":[{"type":"shield","duration":-1,"value":1}],"attackEffects":[{"type":"poison","duration":-1,"value":-1}],"immunity":[]}],"elite":[{"level":0,"health":8,"movement":1,"attack":2,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":1,"health":9,"movement":1,"attack":2,"defenseEffects":[{"type":"shield","duration":-1,"value":1}],"attackEffects":[],"immunity":[]},{"level":2,"health":11,"movement":1,"attack":2,"defenseEffects":[{"type":"shield","duration":-1,"value":1}],"attackEffects":[],"immunity":[]},{"level":3,"health":11,"movement":2,"attack":3,"defenseEffects":[{"type":"shield","duration":-1,"value":1}],"attackEffects":[{"type":"poison","duration":-1,"value":-1}],"immunity":[]},{"level":4,"health":13,"movement":2,"attack":4,"defenseEffects":[{"type":"shield","duration":-1,"value":1}],"attackEffects":[{"type":"poison","duration":-1,"value":-1}],"immunity":[]},{"level":5,"health":15,"movement":3,"attack":4,"defenseEffects":[{"type":"shield","duration":-1,"value":1}],"attackEffects":[{"type":"poison","duration":-1,"value":-1}],"immunity":[]},{"level":6,"health":16,"movement":3,"attack":4,"defenseEffects":[{"type":"shield","duration":-1,"value":2}],"attackEffects":[{"type":"poison","duration":-1,"value":-1}],"immunity":[]},{"level":7,"health":18,"movement":3,"attack":5,"defenseEffects":[{"type":"shield","duration":-1,"value":2}],"attackEffects":[{"type":"poison","duration":-1,"value":-1}],"immunity":[]}]}}')	
  ,('b16c9a75-5ca1-4b2e-9235-e9b3976ffcc9', 'jawsOfTheLion', 'Monster - Living Spirit', '{"name":"Living Spirit","code":"living_spirit","kind":"monster","baseStats":{"standard":[{"level":0,"health":3,"movement":2,"attack":2,"defenseEffects":[{"type":"shield","duration":-1,"value":1}],"attackEffects":[],"immunity":[]},{"level":1,"health":4,"movement":2,"attack":2,"defenseEffects":[{"type":"shield","duration":-1,"value":1}],"attackEffects":[],"immunity":[]},{"level":2,"health":5,"movement":3,"attack":2,"defenseEffects":[{"type":"shield","duration":-1,"value":1}],"attackEffects":[],"immunity":[]},{"level":3,"health":6,"movement":3,"attack":3,"defenseEffects":[{"type":"shield","duration":-1,"value":1}],"attackEffects":[],"immunity":[]},{"level":4,"health":6,"movement":3,"attack":3,"defenseEffects":[{"type":"shield","duration":-1,"value":2}],"attackEffects":[],"immunity":[]},{"level":5,"health":8,"movement":3,"attack":3,"defenseEffects":[{"type":"shield","duration":-1,"value":2}],"attackEffects":[],"immunity":[]},{"level":6,"health":9,"movement":3,"attack":4,"defenseEffects":[{"type":"shield","duration":-1,"value":2}],"attackEffects":[],"immunity":[]},{"level":7,"health":12,"movement":3,"attack":4,"defenseEffects":[{"type":"shield","duration":-1,"value":2}],"attackEffects":[],"immunity":[]}],"elite":[{"level":0,"health":5,"movement":3,"attack":3,"defenseEffects":[{"type":"shield","duration":-1,"value":1}],"attackEffects":[],"immunity":[]},{"level":1,"health":5,"movement":3,"attack":3,"defenseEffects":[{"type":"shield","duration":-1,"value":2}],"attackEffects":[],"immunity":[]},{"level":2,"health":7,"movement":4,"attack":3,"defenseEffects":[{"type":"shield","duration":-1,"value":2}],"attackEffects":[],"immunity":[]},{"level":3,"health":8,"movement":4,"attack":4,"defenseEffects":[{"type":"shield","duration":-1,"value":2}],"attackEffects":[],"immunity":[]},{"level":4,"health":8,"movement":4,"attack":4,"defenseEffects":[{"type":"shield","duration":-1,"value":3}],"attackEffects":[],"immunity":[]},{"level":5,"health":11,"movement":4,"attack":4,"defenseEffects":[{"type":"shield","duration":-1,"value":3}],"attackEffects":[],"immunity":[]},{"level":6,"health":13,"movement":4,"attack":5,"defenseEffects":[{"type":"shield","duration":-1,"value":3}],"attackEffects":[],"immunity":[]},{"level":7,"health":17,"movement":4,"attack":5,"defenseEffects":[{"type":"shield","duration":-1,"value":3}],"attackEffects":[],"immunity":[]}]}}')	
  ,('39fa0ed1-f419-4a6b-9d71-a938eb549453', 'jawsOfTheLion', 'Monster - Blood Imp', '{"name":"Blood Imp","code":"blood_imp","kind":"monster","baseStats":{"standard":[{"level":0,"health":3,"movement":2,"attack":1,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":1,"health":4,"movement":2,"attack":1,"defenseEffects":[],"attackEffects":[{"type":"muddle","duration":1,"value":-1}],"immunity":[]},{"level":2,"health":5,"movement":3,"attack":1,"defenseEffects":[],"attackEffects":[{"type":"muddle","duration":1,"value":-1}],"immunity":[]},{"level":3,"health":5,"movement":3,"attack":2,"defenseEffects":[],"attackEffects":[{"type":"muddle","duration":1,"value":-1}],"immunity":[]},{"level":4,"health":7,"movement":3,"attack":2,"defenseEffects":[],"attackEffects":[{"type":"muddle","duration":1,"value":-1}],"immunity":[]},{"level":5,"health":8,"movement":4,"attack":2,"defenseEffects":[],"attackEffects":[{"type":"muddle","duration":1,"value":-1}],"immunity":[]},{"level":6,"health":9,"movement":4,"attack":3,"defenseEffects":[],"attackEffects":[{"type":"muddle","duration":1,"value":-1}],"immunity":[]},{"level":7,"health":12,"movement":4,"attack":3,"defenseEffects":[],"attackEffects":[{"type":"muddle","duration":1,"value":-1}],"immunity":[]}],"elite":[{"level":0,"health":4,"movement":2,"attack":2,"defenseEffects":[],"attackEffects":[{"type":"muddle","duration":1,"value":-1}],"immunity":[]},{"level":1,"health":6,"movement":2,"attack":2,"defenseEffects":[],"attackEffects":[{"type":"muddle","duration":1,"value":-1}],"immunity":[]},{"level":2,"health":7,"movement":3,"attack":2,"defenseEffects":[],"attackEffects":[{"type":"muddle","duration":1,"value":-1}],"immunity":[]},{"level":3,"health":10,"movement":3,"attack":2,"defenseEffects":[],"attackEffects":[{"type":"muddle","duration":1,"value":-1}],"immunity":[]},{"level":4,"health":11,"movement":3,"attack":3,"defenseEffects":[],"attackEffects":[{"type":"muddle","duration":1,"value":-1}],"immunity":[]},{"level":5,"health":13,"movement":4,"attack":3,"defenseEffects":[],"attackEffects":[{"type":"muddle","duration":1,"value":-1}],"immunity":[]},{"level":6,"health":17,"movement":4,"attack":3,"defenseEffects":[],"attackEffects":[{"type":"muddle","duration":1,"value":-1}],"immunity":[]},{"level":7,"health":21,"movement":4,"attack":4,"defenseEffects":[],"attackEffects":[{"type":"muddle","duration":1,"value":-1}],"immunity":[]}]}}')	
  ,('c51cc271-262f-4bd5-ab41-88fcf343b2bf', 'jawsOfTheLion', 'Monster - Blood Monstrosity', '{"name":"Blood Monstrosity","code":"blood_monstrosity","kind":"monster","baseStats":{"standard":[{"level":0,"health":7,"movement":2,"attack":2,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":1,"health":9,"movement":2,"attack":2,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":2,"health":10,"movement":2,"attack":3,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":3,"health":12,"movement":3,"attack":3,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":4,"health":12,"movement":3,"attack":3,"defenseEffects":[{"type":"shield","duration":-1,"value":1}],"attackEffects":[],"immunity":[]},{"level":5,"health":13,"movement":3,"attack":4,"defenseEffects":[{"type":"shield","duration":-1,"value":1}],"attackEffects":[],"immunity":[]},{"level":6,"health":17,"movement":3,"attack":4,"defenseEffects":[{"type":"shield","duration":-1,"value":1}],"attackEffects":[],"immunity":[]},{"level":7,"health":20,"movement":3,"attack":5,"defenseEffects":[{"type":"shield","duration":-1,"value":1}],"attackEffects":[],"immunity":[]}],"elite":[{"level":0,"health":12,"movement":2,"attack":3,"defenseEffects":[],"attackEffects":[],"immunity":[]},{"level":1,"health":12,"movement":2,"attack":3,"defenseEffects":[{"type":"shield","duration":-1,"value":1}],"attackEffects":[],"immunity":[]},{"level":2,"health":15,"movement":2,"attack":4,"defenseEffects":[{"type":"shield","duration":-1,"value":1}],"attackEffects":[],"immunity":[]},{"level":3,"health":18,"movement":3,"attack":4,"defenseEffects":[{"type":"shield","duration":-1,"value":1}],"attackEffects":[],"immunity":[]},{"level":4,"health":18,"movement":3,"attack":4,"defenseEffects":[{"type":"shield","duration":-1,"value":2}],"attackEffects":[],"immunity":[]},{"level":5,"health":20,"movement":3,"attack":5,"defenseEffects":[{"type":"shield","duration":-1,"value":2}],"attackEffects":[],"immunity":[]},{"level":6,"health":23,"movement":3,"attack":6,"defenseEffects":[{"type":"shield","duration":-1,"value":2}],"attackEffects":[],"immunity":[]},{"level":7,"health":23,"movement":3,"attack":6,"defenseEffects":[{"type":"shield","duration":-1,"value":3}],"attackEffects":[],"immunity":[]}]}}')
  
  -- Monster - Bosses
  ,('a5777e6c-a341-43bb-a841-5c4c8d4b2050', 'jawsOfTheLion', 'Monster - Blood Horror', '{"name":"Blood Horror","code":"blood_horror","kind":"monster","baseStats":{"standard":[{"level":0,"health":7,"healthMod":"multi","movement":3,"attack":-1,"attackMod":"add","defenseEffects":[],"attackEffects":[],"immunity":["disarm","muddle","immobilize","stun"]},{"level":1,"health":10,"healthMod":"multi","movement":3,"attack":0,"attackMod":"add","defenseEffects":[],"attackEffects":[],"immunity":["disarm","muddle","immobilize","stun"]},{"level":2,"health":12,"healthMod":"multi","movement":4,"attack":0,"attackMod":"add","defenseEffects":[],"attackEffects":[],"immunity":["disarm","muddle","immobilize","stun"]},{"level":3,"health":15,"healthMod":"multi","movement":4,"attack":1,"attackMod":"add","defenseEffects":[],"attackEffects":[],"immunity":["disarm","muddle","immobilize","stun"]},{"level":4,"health":17,"healthMod":"multi","movement":5,"attack":1,"attackMod":"add","defenseEffects":[],"attackEffects":[],"immunity":["disarm","muddle","immobilize","stun"]},{"level":5,"health":20,"healthMod":"multi","movement":5,"attack":2,"attackMod":"add","defenseEffects":[],"attackEffects":[],"immunity":["disarm","muddle","immobilize","stun"]},{"level":6,"health":23,"healthMod":"multi","movement":5,"attack":3,"attackMod":"add","defenseEffects":[],"attackEffects":[],"immunity":["disarm","muddle","immobilize","stun"]},{"level":7,"health":28,"healthMod":"multi","movement":5,"attack":4,"attackMod":"add","defenseEffects":[],"attackEffects":[],"immunity":["disarm","muddle","immobilize","stun"]}],"elite":[]}}')
  ,('51e1099f-924f-4bf3-a324-560b2a3839e8', 'jawsOfTheLion', 'Monster - First of the Order', '{"name":"First of the Order","code":"first_of_the_order","kind":"monster","baseStats":{"standard":[{"level":0,"health":10,"healthMod":"multi","movement":2,"attack":3,"defenseEffects":[],"attackEffects":[],"immunity":["disarm","immobilize","muddle","stun","curse"]},{"level":1,"health":14,"healthMod":"multi","movement":2,"attack":4,"defenseEffects":[],"attackEffects":[],"immunity":["disarm","immobilize","muddle","stun","curse"]},{"level":2,"health":17,"healthMod":"multi","movement":2,"attack":4,"defenseEffects":[],"attackEffects":[],"immunity":["disarm","immobilize","muddle","stun","curse"]},{"level":3,"health":20,"healthMod":"multi","movement":2,"attack":5,"defenseEffects":[],"attackEffects":[],"immunity":["disarm","immobilize","muddle","stun","curse"]},{"level":4,"health":24,"healthMod":"multi","movement":3,"attack":5,"defenseEffects":[],"attackEffects":[],"immunity":["disarm","immobilize","muddle","stun","curse"]},{"level":5,"health":28,"healthMod":"multi","movement":3,"attack":6,"defenseEffects":[],"attackEffects":[],"immunity":["disarm","immobilize","muddle","stun","curse"]},{"level":6,"health":32,"healthMod":"multi","movement":3,"attack":7,"defenseEffects":[],"attackEffects":[],"immunity":["disarm","immobilize","muddle","stun","curse"]},{"level":7,"health":36,"healthMod":"multi","movement":3,"attack":8,"defenseEffects":[],"attackEffects":[],"immunity":["disarm","immobilize","muddle","stun","curse"]}],"elite":[]}}')	
  ,('0bc4bb6f-5550-41bd-aabe-ef0727d7acfa', 'jawsOfTheLion', 'Monster - Blood Tumor', '{"name":"Blood Tumor","code":"blood_tumor","kind":"monster","baseStats":{"standard":[{"level":0,"health":7,"healthMod":"multi","movement":0,"attack":-1,"attackMod":"add","defenseEffects":[],"attackEffects":[],"immunity":["disarm","muddle","stun"]},{"level":1,"health":10,"healthMod":"multi","movement":0,"attack":0,"attackMod":"add","defenseEffects":[],"attackEffects":[],"immunity":["disarm","muddle","stun"]},{"level":2,"health":12,"healthMod":"multi","movement":0,"attack":0,"attackMod":"add","defenseEffects":[],"attackEffects":[],"immunity":["disarm","muddle","stun"]},{"level":3,"health":15,"healthMod":"multi","movement":0,"attack":1,"attackMod":"add","defenseEffects":[],"attackEffects":[],"immunity":["disarm","muddle","stun"]},{"level":4,"health":17,"healthMod":"multi","movement":0,"attack":1,"attackMod":"add","defenseEffects":[],"attackEffects":[],"immunity":["disarm","muddle","stun"]},{"level":5,"health":20,"healthMod":"multi","movement":0,"attack":2,"attackMod":"add","defenseEffects":[],"attackEffects":[],"immunity":["disarm","muddle","stun"]},{"level":6,"health":23,"healthMod":"multi","movement":0,"attack":2,"attackMod":"add","defenseEffects":[],"attackEffects":[],"immunity":["disarm","muddle","stun"]},{"level":7,"health":28,"healthMod":"multi","movement":0,"attack":3,"attackMod":"add","defenseEffects":[],"attackEffects":[],"immunity":["disarm","muddle","stun"]}],"elite":[]}}')
  
  -- Monster Modifier Deck
  ,('6cf6168c-07f8-4eba-aa6c-826dd516f054', 'jawsofTheLion', 'Monster - Modifier Deck', '[{"type":"add","value":2,"isCurse":false,"isBlessing":false,"triggerShuffle":false},{"type":"add","value":2,"isCurse":false,"isBlessing":false,"triggerShuffle":false},{"type":"add","value":1,"isCurse":false,"isBlessing":false,"triggerShuffle":false},{"type":"add","value":1,"isCurse":false,"isBlessing":false,"triggerShuffle":false},{"type":"add","value":1,"isCurse":false,"isBlessing":false,"triggerShuffle":false},{"type":"add","value":1,"isCurse":false,"isBlessing":false,"triggerShuffle":false},{"type":"add","value":1,"isCurse":false,"isBlessing":false,"triggerShuffle":false},{"type":"add","value":0,"isCurse":false,"isBlessing":false,"triggerShuffle":false},{"type":"add","value":0,"isCurse":false,"isBlessing":false,"triggerShuffle":false},{"type":"add","value":0,"isCurse":false,"isBlessing":false,"triggerShuffle":false},{"type":"add","value":0,"isCurse":false,"isBlessing":false,"triggerShuffle":false},{"type":"add","value":-1,"isCurse":false,"isBlessing":false,"triggerShuffle":false},{"type":"add","value":-1,"isCurse":false,"isBlessing":false,"triggerShuffle":false},{"type":"add","value":-1,"isCurse":false,"isBlessing":false,"triggerShuffle":false},{"type":"add","value":-1,"isCurse":false,"isBlessing":false,"triggerShuffle":false},{"type":"add","value":-1,"isCurse":false,"isBlessing":false,"triggerShuffle":false},{"type":"add","value":-2,"isCurse":false,"isBlessing":false,"triggerShuffle":false},{"type":"add","value":-2,"isCurse":false,"isBlessing":false,"triggerShuffle":false},{"type":"cancel","value":0,"isCurse":false,"isBlessing":false,"triggerShuffle":true},{"type":"multiply","value":2,"isCurse":false,"isBlessing":false,"triggerShuffle":true}]')

;


/*

,('', '', '', '')


{
	"name":"",
	"code":"",
	"kind":"monster",
	"baseStats":{
		"standard":[
			{"level":0,"health":0,"movement":0,"attack":0,"defenseEffects":[],"attackEffects":[],"immunity":[]},
			"1":{"health":0,"movement":0,"attack":0,"defenseEffects":[],"attackEffects":[],"immunity":[]},
			"2":{"health":0,"movement":0,"attack":0,"defenseEffects":[],"attackEffects":[],"immunity":[]},
			"3":{"health":0,"movement":0,"attack":0,"defenseEffects":[],"attackEffects":[],"immunity":[]},
			"4":{"health":0,"movement":0,"attack":0,"defenseEffects":[],"attackEffects":[],"immunity":[]},
			"5":{"health":0,"movement":0,"attack":0,"defenseEffects":[],"attackEffects":[],"immunity":[]},
			"6":{"health":0,"movement":0,"attack":0,"defenseEffects":[],"attackEffects":[],"immunity":[]},
			"7":{"health":0,"movement":0,"attack":0,"defenseEffects":[],"attackEffects":[],"immunity":[]}
		},
		"elite":{
			{"level":0,"health":0,"movement":0,"attack":0,"defenseEffects":[],"attackEffects":[],"immunity":[]},
			"1":{"health":0,"movement":0,"attack":0,"defenseEffects":[],"attackEffects":[],"immunity":[]},
			"2":{"health":0,"movement":0,"attack":0,"defenseEffects":[],"attackEffects":[],"immunity":[]},
			"3":{"health":0,"movement":0,"attack":0,"defenseEffects":[],"attackEffects":[],"immunity":[]},
			"4":{"health":0,"movement":0,"attack":0,"defenseEffects":[],"attackEffects":[],"immunity":[]},
			"5":{"health":0,"movement":0,"attack":0,"defenseEffects":[],"attackEffects":[],"immunity":[]},
			"6":{"health":0,"movement":0,"attack":0,"defenseEffects":[],"attackEffects":[],"immunity":[]},
			"7":{"health":0,"movement":0,"attack":0,"defenseEffects":[],"attackEffects":[],"immunity":[]}
		}
	}
}


{
	"name":"",
	"code":"",
	"kind":"monster",
	"baseStats":{
		"standard":[
			{"level":0,"health":0,"healthMod":"","movement":0,"moveMod":"","attack":0,"attackMod":"","defenseEffects":[],"attackEffects":[],"immunity":[]},
			"1":{"health":0,"healthMod":"","movement":0,"moveMod":"","attack":0,"attackMod":"","defenseEffects":[],"attackEffects":[],"immunity":[]},
			"2":{"health":0,"healthMod":"","movement":0,"moveMod":"","attack":0,"attackMod":"","defenseEffects":[],"attackEffects":[],"immunity":[]},
			"3":{"health":0,"healthMod":"","movement":0,"moveMod":"","attack":0,"attackMod":"","defenseEffects":[],"attackEffects":[],"immunity":[]},
			"4":{"health":0,"healthMod":"","movement":0,"moveMod":"","attack":0,"attackMod":"","defenseEffects":[],"attackEffects":[],"immunity":[]},
			"5":{"health":0,"healthMod":"","movement":0,"moveMod":"","attack":0,"attackMod":"","defenseEffects":[],"attackEffects":[],"immunity":[]},
			"6":{"health":0,"healthMod":"","movement":0,"moveMod":"","attack":0,"attackMod":"","defenseEffects":[],"attackEffects":[],"immunity":[]},
			"7":{"health":0,"healthMod":"","movement":0,"moveMod":"","attack":0,"attackMod":"","defenseEffects":[],"attackEffects":[],"immunity":[]}
		},
		"elite":{}
	}
}

*/