kind: pipeline
type: kubernetes
name: Build-Only

trigger:
  branch:
    exclude:
      - master
      - dev
  event:
    - push
    - pr

steps:
  - name: build-only-utility
    image: registry.casperinc.net/docker:dind
    commands:
      # Login to Nexus Registry
      - mkdir /root/.docker
      - echo $$NEXUS_CREDS | base64 -d > /root/.docker/config.json
      - docker login registry.casperinc.net
      - docker login docker-hosted.casperinc.net
      - cd ght-service/
      # Build and tag docker image
      - docker build -t ght-service:latest  .
    environment:
      NEXUS_CREDS:
        from_secret: docker_config
    volumes:
      - name: dockersock
        path: /var/run/
          
  - name: build-only-client
    image: registry.casperinc.net/docker:dind
    commands:
      # Login to Nexus Registry
      - mkdir /root/.docker
      - echo $$NEXUS_CREDS | base64 -d > /root/.docker/config.json
      - docker login registry.casperinc.net
      - docker login docker-hosted.casperinc.net
      - cd ght-client/
      # Build and tag docker image
      - docker build -t ght-client:latest  .
    environment:
      NEXUS_CREDS:
        from_secret: docker_config
    volumes:
      - name: dockersock
        path: /var/run/

volumes:
  - name: dockersock
    host:
      path: /var/run/

image_pull_secrets:
  - pipeline_image_registry_secrets


# Credentials to pull pipeline images from registry
---
kind: secret
name: pipeline_image_registry_secrets
get:
  path: regcred
  name: .dockerconfigjson

# Credentials to push built images to registry
---
kind: secret
name: docker_config
get:
  path: nexus-credentials
  name: DOCKERCONFIGASBASE64
---
kind: secret
name: nexus_cred_base64
get:
  path: nexus-credentials
  name: DOCKERCREDSDOUBLE64