---
kind: pipeline
type: kubernetes
name: Build-Only

trigger:
  branch:
    exclude:
      - master
      - dev

  event:
    - push
    - pr

steps:

  - name: build-only-service
    image: plugins/docker
    settings:
      dry_run: true
      repo: harbor.casperinc.net/library/ght/ght-service
      registry: harbor.casperinc.net
      username:
        from_secret: registry-username
      password:
        from_secret: registry-password
      context: ./ght-service/
      dockerfile: ./ght-service/Dockerfile
      build_args:
        - REGISTRY=harbor.casperinc.net/microsoft/
      
  - name: build-only-client
    image: plugins/docker
    settings:
      dry_run: true
      repo: harbor.casperinc.net/library/ght/ght-client
      registry: harbor.casperinc.net
      username:
        from_secret: registry-username
      password:
        from_secret: registry-password
      context: ./ght-client/
      dockerfile: ./ght-client/Dockerfile
      build_args:
        - REGISTRY=harbor.casperinc.net/docker-hub/library/


---
kind: pipeline
type: kubernetes
name: Build-Push-Deploy

trigger:
  branch:
    include:
      - dev

  event:
    - push
    - merge

steps:

  - name: send-tags-to-tags-file
    image: bash
    commands:
      - echo -n "${DRONE_BRANCH//\//-}-${DRONE_COMMIT_SHA:0:8}, ${DRONE_BRANCH//\//-}-latest, " > .tags
      - cat /drone/src/version >> .tags

  - name: "Service: Build and Push Image"
    image: plugins/docker
    settings:
      dry_run: false
      repo: harbor.casperinc.net/library/ght/ght-service
      registry: harbor.casperinc.net
      tags: 
        # - ${DRONE_BRANCH//\//-}-${DRONE_COMMIT_SHA:0:8}
        # - ${DRONE_BRANCH//\//-}-latest
      username:
        from_secret: registry-username
      password:
        from_secret: registry-password
      context: ./ght-service/
      dockerfile: ./ght-service/Dockerfile
      build_args:
        - REGISTRY=harbor.casperinc.net/microsoft/

  - name: "Client: Build and Push Image"
    image: plugins/docker
    settings:
      dry_run: false
      repo: harbor.casperinc.net/library/ght/ght-client
      registry: harbor.casperinc.net
      tags:
        # - ${DRONE_BRANCH//\//-}-${DRONE_COMMIT_SHA:0:8}
        # - ${DRONE_BRANCH//\//-}-latest
      username:
        from_secret: registry-username
      password:
        from_secret: registry-password
      context: ./ght-client/
      dockerfile: ./ght-client/Dockerfile
      build_args:
        - REGISTRY=harbor.casperinc.net/docker-hub/library/

  - name: "EF: Update NPRD Database"
    when:
      branch:
        - dev
    image: mcr.microsoft.com/dotnet/sdk:6.0
    environment:
      DB_SERVER:
        from_secret: creds-nprd-db-server
      DB_PORT:
        from_secret: creds-nprd-db-port
      DB_DATABASE:
        from_secret: creds-nprd-db-database
      DB_USER:
        from_secret: creds-nprd-db-user
      DB_PASSWORD:
        from_secret: creds-nprd-db-password
    commands:
      - cd /drone/src/ght-service
      - export PATH="$PATH:/root/.dotnet/tools"
      - dotnet tool install --global dotnet-ef --version 6.0.3
      - dotnet restore
      - dotnet ef database update --project ./Database/ght-database.csproj --startup-project ./Service

---
kind: secret
name: registry-username
get:
  path: harbor-registry
  name: USERNAME
---
kind: secret
name: registry-password
get:
  path: harbor-registry
  name: PASSWORD
---
kind: secret
name: creds-nprd-db-user
get:
  path: ght-nprd
  name: DB_USER
---
kind: secret
name: creds-nprd-db-password
get:
  path: ght-nprd
  name: DB_PASSWORD
---
kind: secret
name: creds-nprd-db-database
get:
  path: ght-nprd
  name: DB_DATABASE
---
kind: secret
name: creds-nprd-db-server
get:
  path: ght-nprd
  name: DB_SERVER
---
kind: secret
name: creds-nprd-db-port
get:
  path: ght-nprd
  name: DB_PORT