version: '3'
services:
  ght-client:
    build: 
      context: ./ght-client
      args:
        BUILD_ENV: local
    image: ght-client:latest
    ports:
      - "5025:80"
  ght-service:
    image: harbor.casperinc.net/library/ght/ght-service:dev-latest
    ports:
      - "5020:5020"
    environment:
      ASPNETCORE_URLS: http://+:5020
      ASPNETCORE_ENVIRONMENT: Development
      CORS_ALLOWED_ORIGINS: http://localhost:5025,http://localhost.fiddler:5025
      AUTH_ENABLED: "true"
      AUTH_AUTHORITY: https://iam.casperinc.net/realms/nprd
      AUTH_AUDIENCE: gloomhaven-tracker-api
      HTTP_LOGGING_ENABLED: "true"
      DB_SERVER: host.docker.internal
      DB_PORT: 5432
      DB_DATABASE: ght-db
      DB_USER: pguser
      DB_PASSWORD: pguser
      DB_SEED_DATA: "true"
  ght-database:
    image: postgres:14-alpine3.14
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: ght-db
volumes:
  db-data:
    driver: local