{{- if .Values.ght.dopplerSecrets.enabled -}}
{{- range .Values.ght.dopplerSecrets.secrets }}
---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: {{ .dopplerSecretName }}
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: {{ .dopplerSecretToken }}
  managedSecret:
    name: {{ .deploySecretName }}
    namespace: {{ $.Release.Namespace | default }}
{{- end}}
{{- end}}