apiVersion: apps/v1
kind: Deployment
metadata:
  name: ght-testingdb-__COMMITSHA__
  labels:
    app.kubernetes.io/name: ght-testingdb-__COMMITSHA__
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ght-testingdb-__COMMITSHA__
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ght-testingdb-__COMMITSHA__
    spec:
      imagePullSecrets:
        - name: harbor-regcred-svc-drone
      containers:
        - name: ght-testingdb-__COMMITSHA__
          image: harbor.casperinc.net/library/ght/testingdb:dev-latest
          imagePullPolicy: Always
          ports:
            - name: tcp
              containerPort: 5432
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 250m
              memory: 248Mi
          env:
          - name: POSTGRES_USER 
            value: __DB_USER__
          - name: POSTGRES_PASSWORD 
            value: pguser
          - name: POSTGRES_DB 
            value: __DB_DATABASE__
---
apiVersion: v1
kind: Service
metadata:
  name: ght-testingdb-__COMMITSHA__
  labels:
    app.kubernetes.io/name: ght-testingdb-__COMMITSHA__
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector:
    app.kubernetes.io/name: ght-testingdb-__COMMITSHA__
